version: '2'
services:
  redis:
    image: redis
  db:
    image: postgres
  web:
    build: .
    command: /docker/start
    volumes:
      - .:/jarvis
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis